# Server Configuration
server.port=8080

# Spring Boot Actuator Monitoring Endpoints
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

# Micrometer Graphite Export configuration
management.metrics.export.graphite.enabled=true
management.metrics.export.graphite.host=graphite-server
management.metrics.export.graphite.port=2003
management.metrics.export.graphite.step=10s
management.metrics.export.graphite.protocol=pickled
